#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "***************************************"
echo "* Bootstrapping Manhattan Environment *"
echo "***************************************"
echo ""

#mongodb snapshot sources
apt-add-repository 'deb http://downloads.mongodb.org/distros/ubuntu 10.10 10gen'
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
apt-get -y update
apt-get -y upgrade

# system dependencies
apt-get -y install git \
					nginx \
					mongodb \
					python-pip \
					python-dev \
					build-essential \
					python-setuptools \

# virtual env
pip install virtualenv
virtualenv dev
. dev/bin/activate

# python dependencies
pip install Flask \
				flup \
				pymongo \
				py-bcrypt \

ln -s $(pwd)/dev/bin/python /usr/bin/manhattan.python

chown -R ubuntu /home/ubuntu/

# deploy nginx configuration
cp nginx/nginx.conf /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
mkdir /var/manhattan
mkdir /var/manhattan/log
mkdir /var/manhattan/log/nginx
mkdir /var/www/log
chown -R ubuntu /var/www

echo ""
echo "***************************"
echo "* Deploying core services *"
echo "***************************"
echo ""

mkdir /data/db #mongodb | temp -> replace with its own deployment

cp upstart/*.conf /etc/init/

cp nginx/cert.crt /var/www/
cp nginx/cert.key /var/www/

cp fcgi/*.fcgi /var/www/

echo ""
echo "********************"
echo "* Manhattan::Done! *"
echo "********************"
echo ""
