#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "******************************"
echo "* Upgrading Styx Environment *"
echo "******************************"
echo ""

chown -R ubuntu .

# deploy nginx configuration
cp nginx/nginx.conf /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
chown -R ubuntu /var/www

echo ""
echo "**************************"
echo "* Updating core services *"
echo "**************************"
echo ""

cp upstart/*.conf /etc/init/

cp nginx/cert.crt /var/www/
cp nginx/cert.key /var/www/

cp fcgi/cerberus.fcgi /var/www/cerberus.fcgi
cp fcgi/hermes.fcgi /var/www/hermes.fcgi
cp fcgi/gaia.fcgi /var/www/gaia.fcgi

sh restart

echo ""
echo "***************"
echo "* styx::Done! *"
echo "***************"
echo ""
