#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** styx *** starting cerberus..."
start cerberus.styx
echo "*** styx *** starting hermes..."
start hermes.styx
echo "*** styx *** starting gaia..."
start gaia.styx
echo "*** styx *** starting nginx..."
start nginx.styx
echo "*** styx *** starting mongodb..."
start mongodb.styx
