#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "************************************"
echo "* Bootstrapping memoize Environment *"
echo "************************************"
echo ""

#mongodb snapshot sources
apt-add-repository 'deb http://downloads.mongodb.org/distros/ubuntu 10.10 10gen'
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
apt-get -y update
apt-get -y upgrade

# system and python dependencies
apt-get -y install git \
                   curl \
                   nginx \
                   mongodb \
                   openssl \
                   uuid-dev \
                   python2.7 \
                   libssl-dev \
                   libgif-dev \
                   python-pip \
                   libjpeg-dev \
                   libevent-dev \
                   python2.7-dev \
                   build-essential \
                   rabbitmq-server \
                   libfreetype6-dev \
                   python-setuptools \

# stop the ubuntu-managed rabbitmq-server
rabbitmqctl stop

# set up zeromq
curl http://download.zeromq.org/zeromq-2.1.3.tar.gz | tar xz && cd zeromq-*
./configure
make
sudo make install
cd ..
rm zeromq*.tar.gz
sudo cp -R /usr/local/lib/* /usr/lib/* # zeromq libraries

# set up node
git clone https://github.com/joyent/node.git && cd node
./configure
make
sudo make install
cd ..

# install node packages
curl http://npmjs.org/install.sh | sudo sh
rm install.sh
sudo npm install zeromq
sudo npm install socket.io

# virtual env
pip install virtualenv
virtualenv -p python2.7 --no-site-packages --distribute --clear env
. env/bin/activate

# python dependencies
pip install PIL \
            Flask \
            pyzmq \
            celery \
            gevent \
            pymongo \
            eventlet \
            gunicorn \
            py-bcrypt \
            flask-uploads \

sh script/celeryd

sh script/reconfig

sh script/rabbitmq
