#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "************************************"
echo "* Bootstrapping memoize Environment *"
echo "************************************"
echo ""

#mongodb snapshot sources
apt-add-repository 'deb http://downloads.mongodb.org/distros/ubuntu 10.10 10gen'
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
apt-get -y update
apt-get -y upgrade

# add the celery config file to PYTHONPATH
echo "Adding celery config file to PYTHONPATH"
export PYTHONPATH=$(pwd)/celery:$PYTHONPATH
echo "export PYTHONPATH=$(pwd)/celery:\$PYTHONPATH" >> ~/.bashrc

# system and python dependencies
apt-get -y install git \
                    nginx \
                    libjpeg \
                    mongodb \
                    python2.7 \
                    libgif-dev \
                    python-pip \
                    libjpeg-dev \
                    libevent-dev \
                    python2.7-dev \
                    build-essential \
                    rabbitmq-server \
                    libfreetype6-dev \
                    python-setuptools \


# virtual env
pip install virtualenv
virtualenv -p python2.7 --no-site-packages --distribute --clear env
. env/bin/activate

# python dependencies
pip install PIL \
            Flask \
            celery \
            gevent \
            pymongo \
            eventlet \
            gunicorn \
            py-bcrypt \
            flask-uploads \

sh script/reconfig
