#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

rabbitmqctl add_user monet monet
rabbitmqctl add_vhost monetvhost
rabbitmqctl set_permissions -p monetvhost monet ".*" ".*" ".*"
