#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "***********************************"
echo "* Configuring monet Environment *"
echo "***********************************"
echo ""

chown -R ubuntu /home/ubuntu/

ln -s $(pwd)/env/bin/python /usr/bin/monet.python
ln -s $(pwd)/env/bin/gunicorn /usr/bin/monet.gunicorn

# deploy nginx configuration
cp nginx/nginx.conf /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default

#install nginx certs
cp nginx/cert.crt /var/www/
cp nginx/cert.key /var/www/

#deploy mongodb dir structure
mkdir -p /var/www/log
mkdir -p /var/www/db
mkdir -p /var/www/files/thumb
mkdir -p /var/www/files/static

#copy over static resources
echo "installing static files..."
cp -R static/* /var/www/files/static/
cp -R static/images/unprocessed.jpg /var/www/files/thumb

chown -R ubuntu /var/www

echo ""
echo "****************************"
echo "* Installing core services *"
echo "****************************"
echo ""

sh script/stop

cp upstart/*.conf /etc/init/

sh script/start

echo ""
echo "*****************"
echo "* monet::Done! *"
echo "*****************"
echo ""
