#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo ""
echo "********************************"
echo "* Upgrading memoize Environment *"
echo "********************************"
echo ""

chown -R ubuntu /home/ubuntu/

# deploy nginx configuration
cp nginx/nginx.conf /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
chown -R ubuntu /var/www

echo ""
echo "**************************"
echo "* Updating core services *"
echo "**************************"
echo ""

sh script/stop

cp upstart/*.conf /etc/init/

sh script/start

echo ""
echo "*****************"
echo "* memoize::Done! *"
echo "*****************"
echo ""
