#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** collate *** starting client..."
restart client.collate
echo "*** collate *** starting nginx..."
restart nginx.collate
echo "*** collate *** starting mongodb..."
restart mongodb.collate
