#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** stream *** starting client..."
restart client.stream
echo "*** stream *** starting nginx..."
restart nginx.stream
echo "*** stream *** starting mongodb..."
restart mongodb.stream
