#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** stream *** starting client..."
start client.stream
echo "*** stream *** starting nginx..."
start nginx.stream
echo "*** stream *** starting mongodb..."
start mongodb.stream
