#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

initctl reload-configuration

echo "*** monet *** starting mongodb..."
start mongodb.monet
echo "*** monet *** starting rabbitmq..."
start rabbitmq.monet
echo "*** monet *** starting live..."
start live.monet
echo "*** monet *** starting celery..."
start celery.monet
echo "*** monet *** starting client..."
start client.monet
echo "*** monet *** starting nginx..."
start nginx.monet
