#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** monet *** stopping nginx..."
stop nginx.monet
echo "*** monet *** stopping client..."
stop client.monet
echo "*** monet *** stopping celery..."
stop celery.monet
echo "*** monet *** stopping live..."
stop live.monet
echo "*** monet *** stopping rabbitmq..."
stop rabbitmq.monet
echo "*** monet *** stopping mongodb..."
stop mongodb.monet
