#!/bin/bash

if [ `whoami` != root ]; then
	echo Please run this script as root, or using sudo
	exit
fi

echo "*** memoize *** stopping nginx..."
stop nginx.memoize
echo "*** memoize *** stopping client..."
stop client.memoize
echo "*** memoize *** stopping celery..."
stop celery.memoize
echo "*** memoize *** stopping rabbitmq..."
stop rabbitmq.memoize
echo "*** memoize *** stopping mongodb..."
stop mongodb.memoize
